version: '1'

services:

  mysql:
    image: mysql:5.6.41
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
    - default
    expose:
    - "3306"
    ports:
    - "3306:3306"

  basa-backend:
    image: dongjiang1989/basa-backend:latest
    command: /opt/basa/backend
    environment:
      GOPATH: "/go"
    volumes:
    - ./conf/app.conf:/opt/basa/conf/app.conf
    depends_on:
    - mysql
    restart: always
    networks:
    - default
    ports:
    - "8080:8080"

  basa-frontend:
    image: dongjiang1989/basa-frontend:latest
    volumes:
    - ./conf/config.js:/usr/local/openresty/nginx/html/config.js
    depends_on:
    - base-backend
    restart: always
    networks:
    - default
    ports:
    - "4200:80"
